---
  pool: devpool

  trigger: 
    - main
  variables:  
    JAVA_HOME_8_X64: '/usr/lib/jvm/java-8-openjdk-amd64'    

  stages:
    - stage: buildstage
      displayName: mavenbuild
      jobs:
        - job: maven
          displayName: mavenjob
          steps: 
            - task: Maven@3
              inputs:
                mavenPOMFile: 'pom.xml'
                goals: 'package' 
                publishJUnitResults: true 
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                jdkVersionOption: '1.8'