---
  pool: devpool


  trigger:
    - master
  variables:
    JAVA_HOME_8_X64: '/usr/lib/jvm/java-8-openjdk-amd64'  
  
  resources:
    repositories:
      - repository: azuredevopsparameters
        endpoint: github_id
        ref: 'refs/heads/master'
        name: srinudammalapati/azuredevops
        type: github  

        
  stages:
    - template: azuredevopstemplate.yaml@azuredevopsparameters
      parameters:
        goal: package
        jdkVersionoption: "1.8"
        javadirectory: /usr/lib/jvm/java-8-openjdk-amd64/
  
  
  
  
